# Generated by Django 5.1.2 on 2025-01-18 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_remove_customer_cliente_observacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('orcamento_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Orçamento')),
                ('orcamento_endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('orcamento_endereco_numero', models.CharField(max_length=15, verbose_name='Número')),
                ('orcamento_bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('orcamento_cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('orcamento_uf', models.CharField(max_length=2, verbose_name='UF')),
                ('orcamento_fone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('orcamento_data_inicio', models.DateField(verbose_name='Data Início')),
                ('orcamento_periodo', models.CharField(choices=[('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal')], max_length=10, verbose_name='Período')),
                ('orcamento_data_final', models.DateField(verbose_name='Data Final')),
                ('orcamento_valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'db_table': 'ORCAMENTO',
            },
        ),
    ]
