# Generated by Django 5.1.2 on 2024-11-16 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('equipamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipamento_nome_equipamento_ferramenta', models.CharField(max_length=100, verbose_name='Nome do Equipamento')),
                ('equipamento_identificacao_placa', models.CharField(max_length=100, unique=True, verbose_name='Identificação/Placa')),
                ('equipamento_detalhamento', models.TextField(blank=True, null=True, verbose_name='Detalhamento')),
                ('equipamento_caminho_imagem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho da Imagem')),
                ('equipamento_quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('equipamento_valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('equipamento_data_compra', models.DateField(blank=True, null=True, verbose_name='Data da Compra')),
                ('equipamento_data_garantia', models.DateField(blank=True, null=True, verbose_name='Data da Garantia')),
                ('equipamento_prazo_revisao', models.DateField(blank=True, null=True, verbose_name='Prazo de Revisão')),
                ('equipamento_nota_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal')),
                ('equipamento_ativo', models.CharField(choices=[('TRUE', 'Ativo'), ('FALSE', 'Inativo')], max_length=5, verbose_name='Ativo')),
                ('equipamento_valor_diaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Diária')),
                ('equipamento_valor_semanal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Semanal')),
                ('equipamento_valor_quinzenal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Quinzenal')),
                ('equipamento_valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.fornecedor')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'db_table': 'EQUIPAMENTO_FERRAMENTA',
            },
        ),
    ]
