# Generated by Django 5.1.2 on 2024-11-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipamento',
            table='EQUIPAMENTO_FER RAMENTA',
        ),
    ]
