# Generated by Django 5.1.2 on 2024-11-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipamento_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipamento',
            table='EQUIPAMENTO_FERRAMENTA',
        ),
    ]
