# Generated by Django 5.1.2 on 2025-01-18 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipamento_table'),
        ('supplier', '0002_alter_fornecedor_options_alter_fornecedor_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='equipamento_detalhamento',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Detalhamento'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.fornecedor'),
        ),
    ]
