# Generated by Django 5.1.2 on 2025-01-18 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_remove_customer_cliente_observacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('aluguel_id', models.AutoField(primary_key=True, serialize=False)),
                ('aluguel_data_retirada', models.DateField(verbose_name='Data de Retirada')),
                ('aluguel_endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('aluguel_endereco_numero', models.CharField(max_length=15, verbose_name='Número')),
                ('aluguel_bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('aluguel_cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('aluguel_uf', models.CharField(max_length=2, verbose_name='UF')),
                ('aluguel_fone1', models.CharField(max_length=20, verbose_name='Telefone')),
                ('aluguel_periodo', models.CharField(choices=[('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal')], max_length=9, verbose_name='Período')),
                ('aluguel_data_final', models.DateField(verbose_name='Data Final')),
                ('aluguel_valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'db_table': 'ALUGUEL',
            },
        ),
    ]
