# Generated by Django 5.1.2 on 2025-01-18 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluguel', '0001_initial'),
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='orcamento',
            field=models.ForeignKey(blank=True, db_column='orcamento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orcamento.orcamento'),
        ),
    ]
