# Generated by Django 5.1.2 on 2024-11-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('fornecedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('fornecedor_nome_razao_social', models.CharField(max_length=100, verbose_name='Nome/Razão Social')),
                ('fornecedor_cpf_cnpj', models.CharField(max_length=20, unique=True, verbose_name='CPF/CNPJ')),
                ('fornecedor_email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('fornecedor_endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('fornecedor_endereco_numero', models.CharField(max_length=15, verbose_name='Número')),
                ('fornecedor_bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('fornecedor_cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('fornecedor_uf', models.CharField(max_length=2, verbose_name='UF')),
                ('fornecedor_fone1', models.CharField(max_length=20, verbose_name='Telefone 1')),
                ('fornecedor_fone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2')),
                ('fornecedor_observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('fornecedor_ativo', models.CharField(choices=[('TRUE', 'Ativo'), ('FALSE', 'Inativo')], max_length=5, verbose_name='Ativo')),
                ('fornecedor_tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'FORNECEDOR_PF_PJ',
            },
        ),
    ]
