# Generated by Django 5.1.2 on 2024-11-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'managed': True, 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelTable(
            name='fornecedor',
            table='fornecedor_pf_pj',
        ),
    ]
